name: "[App] Deploy to Production"

on:
  push:
    tags:
      - "*"

jobs:
  build-deploy-production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: yarn install & build
        run: |
          yarn
          yarn workspace request-shared build
          yarn workspace request-ui build
          yarn workspace app build
      - uses: benjlevesque/s3-sync-action@master
        env:
          CI: false
          SOURCE_DIR: "packages/app/build"
          AWS_REGION: eu-west-1
          AWS_S3_BUCKET: baguette-v2.request.network
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
